In [1]:
import torch

In [2]:
# 当从文本语料库中获取随机批次时，需要使用
randint = torch.randint(-100,100,(6,))
randint

tensor([  5,  83, -73, -86, -73,  27])

In [4]:
# make tensor
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
zeros = torch.zeros(2,3)
zeros
# float

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# 标准化浮点数
input = torch.empty(2,3)
input

tensor([[-2.4030e-07,  1.8147e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
# from 3 to 10 with 5 steps
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start = -10,end = 10,steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
a = torch.empty((2,3),dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [23]:
%%time
# observe the diff between cuda and cpu
import numpy as np
import time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time-start_time
print(f"{elapsed_time:.8f}")
# wall time --->actually spend time

0.00100827
CPU times: total: 0 ns
Wall time: 1.01 ms


In [22]:
# 测试Numpy在CPU上的性能与tensor在Cuda上的性能比较
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)

np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()
# 矩阵点乘
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1,np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.02517319
0.12766051


In [24]:
# torch.stack, torch.multinomial, torch.tril, torch.triu, input.T/input.transpose, nn.Linear, torch.cat, F.softmax(show all the examples of functions methods with pytorch docs)


# torch.multinomial
# define a probability tensor
# 本质上是基于你提供的索引的概率分布，即10%的概率为0，90%的概率为1
probabilities = torch.tensor([0.1,0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial  distribution
samples = torch.multinomial (probabilities,num_samples=5,replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1])


In [28]:
# torch.cat----------------connect two tensor to one 
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [32]:
# torch.tril---->remain triangle lower info
# 理解，比如第一行仅仅知道第一个1，这是我们目前已知的，后续的0均为未来信息未知；第二行，已知2，2，第三个未知；--------》确保现有信息不与未来发生交互
torch.tril(torch.tensor([[1,1,1],[2,2,2],[3,3,3]]))

tensor([[1, 0, 0],
        [2, 2, 0],
        [3, 3, 3]])

In [33]:
# torch.tril---->remain triangle upper info
torch.triu(torch.tensor([[1,1,1],[2,2,2],[3,3,3]]))

tensor([[1, 1, 1],
        [0, 2, 2],
        [0, 0, 3]])

In [38]:
# torch.masked_fill 掩码操作，接收的第一个参数为mask。将mask中为true的部分设置为第二个参数value的值
torch.tensor([[1.,2.,3.,4.,5.],[2.,3.,4.,5.,6.],[1.,2.,3.,4.,5.],[2.,3.,4.,5.,6.],[1.,2.,3.,4.,5.]]).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))

tensor([[1., -inf, -inf, -inf, -inf],
        [2., 3., -inf, -inf, -inf],
        [1., 2., 3., -inf, -inf],
        [2., 3., 4., 5., -inf],
        [1., 2., 3., 4., 5.]])

In [40]:
# torch.exp对tensor中的值做指数运算
torch.exp(torch.tril(torch.ones(3,3)))

tensor([[2.7183, 1.0000, 1.0000],
        [2.7183, 2.7183, 1.0000],
        [2.7183, 2.7183, 2.7183]])

In [42]:
# torch.transpose 转换维度
input =  torch.zeros(2,3,4)
# 转换第0维和第2维
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [43]:
# torch.stack----->如何将同一批次的块堆叠在一起
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [46]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([ 5.8815, -1.8201,  3.4770], grad_fn=<SqueezeBackward4>)


In [47]:
# softmax translate all value to the only value between zero and one
import torch.nn.functional as F
# Create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])
# Apply softmax using torch.nn.functional.softmax()
# dim = 0；只是一条直线
softmax_output = F.softmax(tensor1,dim=0)
# e^1+e^2+e^3 = 29.95;e^1/29.95 = 0.09;e^2/29.95 = 0.2447;e^3/29.95 = 0.6652
# 查看各部分的指数占总和的全部
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [50]:
# Initialize an embedding layer
vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size,embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1,5,3,2])

# Apply the embedding layer
embedding_output = embedding(input_indices)

# The output will be a tensor of shape(4,100) where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedding_output.shape)
# 实际上是每一个char都被嵌入为一个100维的向量

torch.Size([4, 100])


In [53]:
# matrix dot multiply;signal @ or torch.matmul function
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [58]:
# float can't multiply float
# range 0~1 and the shape of matrix is 3x2
int_64 = torch.randint(1,(3,2)).float()
# typpe int64
float_32 = torch.rand(2,3)
print(int_64.dtype,float_32.dtype)
# type float32
result = torch.matmul(int_64,float_32)
print(result)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# logits解释
a = torch.rand(2,3,5)
x, y, z = a.shape
# 重塑矩阵
a = a.view(y,x,z)
print(a.shape)


torch.Size([3, 2, 5])
